services:
  - type: web
    name: bot-alhoot
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --workers 2 --threads 4
    autoDeploy: true
