services:
  - type: web
    name: bot-mesh
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app -c gunicorn_config.py
    envVars:
      - key: PORT
        value: 8080
      - key: ENV
        value: production
      - key: LINE_CHANNEL_SECRET
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
